test_that("scale_fill_energy 'direction' reverses legend order", {
  skip_if_not_installed("ggplot2"); library(ggplot2)
  d <- data.frame(cat = 1, source = c("Coal","Solar"), value = c(1,1))
  p1 <- ggplot(d, aes(x=cat, y=value, fill=source)) + geom_col() + scale_fill_energy(direction=1, auto_order=TRUE, data=d)
  p2 <- ggplot(d, aes(x=cat, y=value, fill=source)) + geom_col() + scale_fill_energy(direction=-1, auto_order=TRUE, data=d)
  b1 <- ggplot_build(p1); b2 <- ggplot_build(p2)
  lim1 <- b1$plot$scales$get_scales("fill")$get_limits()
  lim2 <- b2$plot$scales$get_scales("fill")$get_limits()
  expect_equal(lim1, c("Coal","Solar"))
  expect_equal(lim2, c("Solar","Coal"))
})
